###Imports, installs & read in data

####installs

In [ ]:
!pip install numpy==1.23.5

Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.11/dist-packages (1.23.5)

In [ ]:
!pip install --force-reinstall spacy thinc

Collecting spacy
  Using cached spacy-3.8.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting thinc
  Using cached thinc-9.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.13-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.5 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.10-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting thinc
  Using cached thinc-8.3.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Using cached srsly-2.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Using cached typer-0.19.2-py3-none-any.whl.metadata (16 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-2.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.12.0-py3-none-any.whl.metadata (83 kB)
Collecting jinja2 (from spacy)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting setuptools (from spacy)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting packaging>=20.0 (from spacy)
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Using cached langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting blis<1.4.0,>=1.3.0 (from thinc)
  Using cached blis-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc)
  Using cached confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy)
  Using cached language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading pydantic_core-2.41.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing-extensions>=4.14.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading charset_normalizer-3.4.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy)
  Downloading smart_open-7.3.1-py3-none-any.whl.metadata (24 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy)
  Downloading marisa_trie-1.3.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy)
  Downloading wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading spacy-3.8.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.0/33.0 MB 45.6 MB/s eta 0:00:00
Downloading thinc-8.3.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 61.9 MB/s eta 0:00:00
Downloading blis-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 126.7 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Downloading cymem-2.0.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (218 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 218.9/218.9 kB 16.5 MB/s eta 0:00:00
Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 17.0 MB/s eta 0:00:00
Downloading murmurhash-1.0.13-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 13.5 MB/s eta 0:00:00
Downloading numpy-2.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 47.9 MB/s eta 0:00:00
Downloading packaging-25.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.3 MB/s eta 0:00:00
Downloading preshed-3.0.10-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (842 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 842.9/842.9 kB 61.4 MB/s eta 0:00:00
Downloading pydantic-2.12.0-py3-none-any.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.7/459.7 kB 42.0 MB/s eta 0:00:00
Downloading pydantic_core-2.41.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 98.8 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 6.9 MB/s eta 0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 66.4 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 6.9 MB/s eta 0:00:00
Downloading typer-0.19.2-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 5.0 MB/s eta 0:00:00
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 5.6 MB/s eta 0:00:00
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 13.7 MB/s eta 0:00:00
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 69.2 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 17.8 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.3/150.3 kB 14.2 MB/s eta 0:00:00
Downloading click-8.3.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 kB 12.2 MB/s eta 0:00:00
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.0 MB/s eta 0:00:00
Downloading idna-3.11-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 7.4 MB/s eta 0:00:00
Downloading language_data-1.3.0-py3-none-any.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 118.6 MB/s eta 0:00:00
Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.4/243.4 kB 24.9 MB/s eta 0:00:00
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading smart_open-7.3.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 6.4 MB/s eta 0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 4.7 MB/s eta 0:00:00
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 12.7 MB/s eta 0:00:00
Downloading marisa_trie-1.3.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 61.8 MB/s eta 0:00:00
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 9.9 MB/s eta 0:00:00
Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 75.1 MB/s eta 0:00:00
Downloading wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 kB 8.9 MB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: cymem, wrapt, wasabi, urllib3, typing-extensions, tqdm, spacy-loggers, spacy-legacy, shellingham, setuptools, pygments, packaging, numpy, murmurhash, mdurl, MarkupSafe, marisa-trie, idna, cloudpathlib, click, charset_normalizer, certifi, catalogue, annotated-types, typing-inspection, srsly, smart-open, requests, pydantic-core, preshed, markdown-it-py, language-data, jinja2, blis, rich, pydantic, langcodes, typer, confection, weasel, thinc, spacy
  Attempting uninstall: cymem
    Found existing installation: cymem 2.0.11
    Uninstalling cymem-2.0.11:
      Successfully uninstalled cymem-2.0.11
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: wasabi
    Found existing installation: wasabi 1.1.3
    Uninstalling wasabi-1.1.3:
      Successfully uninstalled wasabi-1.1.3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.4.0
    Uninstalling urllib3-2.4.0:
      Successfully uninstalled urllib3-2.4.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.14.1
    Uninstalling typing_extensions-4.14.1:
      Successfully uninstalled typing_extensions-4.14.1
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: spacy-loggers
    Found existing installation: spacy-loggers 1.0.5
    Uninstalling spacy-loggers-1.0.5:
      Successfully uninstalled spacy-loggers-1.0.5
  Attempting uninstall: spacy-legacy
    Found existing installation: spacy-legacy 3.0.12
    Uninstalling spacy-legacy-3.0.12:
      Successfully uninstalled spacy-legacy-3.0.12
  Attempting uninstall: shellingham
    Found existing installation: shellingham 1.5.4
    Uninstalling shellingham-1.5.4:
      Successfully uninstalled shellingham-1.5.4
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.19.2
    Uninstalling Pygments-2.19.2:
      Successfully uninstalled Pygments-2.19.2
  Attempting uninstall: packaging
    Found existing installation: packaging 24.2
    Uninstalling packaging-24.2:
      Successfully uninstalled packaging-24.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: murmurhash
    Found existing installation: murmurhash 1.0.13
    Uninstalling murmurhash-1.0.13:
      Successfully uninstalled murmurhash-1.0.13
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
  Attempting uninstall: marisa-trie
    Found existing installation: marisa-trie 1.2.1
    Uninstalling marisa-trie-1.2.1:
      Successfully uninstalled marisa-trie-1.2.1
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
  Attempting uninstall: cloudpathlib
    Found existing installation: cloudpathlib 0.21.1
    Uninstalling cloudpathlib-0.21.1:
      Successfully uninstalled cloudpathlib-0.21.1
  Attempting uninstall: click
    Found existing installation: click 8.2.1
    Uninstalling click-8.2.1:
      Successfully uninstalled click-8.2.1
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.2
    Uninstalling charset-normalizer-3.4.2:
      Successfully uninstalled charset-normalizer-3.4.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.7.14
    Uninstalling certifi-2025.7.14:
      Successfully uninstalled certifi-2025.7.14
  Attempting uninstall: catalogue
    Found existing installation: catalogue 2.0.10
    Uninstalling catalogue-2.0.10:
      Successfully uninstalled catalogue-2.0.10
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.7.0
    Uninstalling annotated-types-0.7.0:
      Successfully uninstalled annotated-types-0.7.0
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.1
    Uninstalling typing-inspection-0.4.1:
      Successfully uninstalled typing-inspection-0.4.1
  Attempting uninstall: srsly
    Found existing installation: srsly 2.5.1
    Uninstalling srsly-2.5.1:
      Successfully uninstalled srsly-2.5.1
  Attempting uninstall: smart-open
    Found existing installation: smart-open 6.4.0
    Uninstalling smart-open-6.4.0:
      Successfully uninstalled smart-open-6.4.0
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.33.2
    Uninstalling pydantic_core-2.33.2:
      Successfully uninstalled pydantic_core-2.33.2
  Attempting uninstall: preshed
    Found existing installation: preshed 3.0.10
    Uninstalling preshed-3.0.10:
      Successfully uninstalled preshed-3.0.10
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 3.0.0
    Uninstalling markdown-it-py-3.0.0:
      Successfully uninstalled markdown-it-py-3.0.0
  Attempting uninstall: language-data
    Found existing installation: language_data 1.3.0
    Uninstalling language_data-1.3.0:
      Successfully uninstalled language_data-1.3.0
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.6
    Uninstalling Jinja2-3.1.6:
      Successfully uninstalled Jinja2-3.1.6
  Attempting uninstall: blis
    Found existing installation: blis 0.7.11
    Uninstalling blis-0.7.11:
      Successfully uninstalled blis-0.7.11
  Attempting uninstall: rich
    Found existing installation: rich 13.9.4
    Uninstalling rich-13.9.4:
      Successfully uninstalled rich-13.9.4
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.24
    Uninstalling pydantic-1.10.24:
      Successfully uninstalled pydantic-1.10.24
  Attempting uninstall: langcodes
    Found existing installation: langcodes 3.5.0
    Uninstalling langcodes-3.5.0:
      Successfully uninstalled langcodes-3.5.0
  Attempting uninstall: typer
    Found existing installation: typer 0.9.4
    Uninstalling typer-0.9.4:
      Successfully uninstalled typer-0.9.4
  Attempting uninstall: confection
    Found existing installation: confection 0.1.5
    Uninstalling confection-0.1.5:
      Successfully uninstalled confection-0.1.5
  Attempting uninstall: weasel
    Found existing installation: weasel 0.4.1
    Uninstalling weasel-0.4.1:
      Successfully uninstalled weasel-0.4.1
  Attempting uninstall: thinc
    Found existing installation: thinc 8.1.12
    Uninstalling thinc-8.1.12:
      Successfully uninstalled thinc-8.1.12
  Attempting uninstall: spacy
    Found existing installation: spacy 3.5.4
    Uninstalling spacy-3.5.4:
      Successfully uninstalled spacy-3.5.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
bg-news-lg 3.5.4 requires spacy<3.6.0,>=3.5.4, but you have spacy 3.8.7 which is incompatible.
pathy 0.11.0 requires smart-open<7.0.0,>=5.2.1, but you have smart-open 7.3.1 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.32.5 which is incompatible.
bigframes 2.10.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.3 which is incompatible.
gradio 5.31.0 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.0 which is incompatible.
langchain-core 0.3.68 requires packaging<25,>=23.2, but you have packaging 25.0 which is incompatible.
mdit-py-plugins 0.4.2 requires markdown-it-py<4.0.0,>=1.0.0, but you have markdown-it-py 4.0.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.3 which is incompatible.

#### imports

In [ ]:
import pandas as pd
import glob
import os
import matplotlib.pyplot as plt
import re
import string
import sys
import nltk
from ast import literal_eval
import time
import math
import numpy as np

####gdrive mount

In [ ]:
from google.colab import drive
drive.mount('drive')

ValueError: mount failed

####downloads

In [ ]:
!pip install https://huggingface.co/sakelariev/bg_news_lg/resolve/main/bg_news_lg-3.5.4-py3-none-any.whl
# !pip install spacy-transformers

####spacy

In [ ]:
import spacy

nlp = spacy.load("bg_news_lg")

#### df load

In [ ]:
df = pd.read_csv(r'drive/My Drive/Colab Notebooks/bg_cds_copyrightsafe.csv')

In [ ]:
df.head(25)

,Source,Utterance,Tokenised,UttLen,MorphTok,def,aorist,imperfect,participle,plural,present
0,https://chitanka.info/book/648-prikazki.txt.zip,Братя Грим,"['братя', 'грим']",2,"['братя', 'грим']",0,0,0,0,0,1
1,https://chitanka.info/book/648-prikazki.txt.zip,Приказки,['приказки'],1,"['приказк', 'и']",0,0,0,0,1,1
2,https://chitanka.info/book/648-prikazki.txt.zip,Умницата Грета,"['умницата', 'грета']",2,"['умница', 'та', 'грета']",1,0,0,0,0,1
3,https://chitanka.info/book/648-prikazki.txt.zip,Имало една готвачка на име Грета.,"['имало', 'една', 'готвачка', 'на', 'име', 'гр...",6,"['има', 'ло', 'едн', 'а', 'готвачка', 'на', 'и...",0,0,0,1,0,1
4,https://chitanka.info/book/648-prikazki.txt.zip,Тя носела обувки с червени токове и като излиз...,"['тя', 'носела', 'обувки', 'с', 'червени', 'то...",23,"['тя', 'носе', 'ла', 'обувки', 'с', 'червен', ...",0,1,1,1,1,1
5,https://chitanka.info/book/648-prikazki.txt.zip,"А щом се върнела вкъщи, още й било толкова вес...","['а', 'щом', 'се', 'върнела', 'вкъщи', 'още', ...",16,"['а', 'щом', 'се', 'върне', 'ла', 'вкъщи', 'ощ...",1,0,0,1,0,1
6,https://chitanka.info/book/648-prikazki.txt.zip,"А тъй като виното събужда желание за ядене, по...","['а', 'тъй', 'като', 'виното', 'събужда', 'жел...",20,"['а', 'тъй', 'като', 'вино', 'то', 'събужд', '...",1,0,0,1,1,1
7,https://chitanka.info/book/648-prikazki.txt.zip,И си казвала:,"['и', 'си', 'казвала']",3,"['и', 'си', 'казва', 'ла']",0,0,0,1,0,1
8,https://chitanka.info/book/648-prikazki.txt.zip,— Всяка готвачка трябва да знае вкуса на гозби...,"['всяка', 'готвачка', 'трябва', 'да', 'знае', ...",9,"['всяк', 'а', 'готвачка', 'трябва', 'да', 'зна...",1,0,0,0,1,1
9,https://chitanka.info/book/648-prikazki.txt.zip,Веднъж господарят й рекъл:,"['веднъж', 'господарят', 'й', 'рекъл']",4,"['веднъж', 'господар', 'ят', 'й', 'рекъ', 'л']",1,0,0,1,0,1
10,https://chitanka.info/book/648-prikazki.txt.zip,"— Грета, довечера ще имам гост.","['грета', 'довечера', 'ще', 'имам', 'гост']",5,"['грета', 'довечера', 'ще', 'имам', 'гост']",0,0,0,0,0,1
11,https://chitanka.info/book/648-prikazki.txt.zip,Опечи две хубави пилета!,"['опечи', 'две', 'хубави', 'пилета']",4,"['опеч', 'и', 'две', 'хубав', 'и', 'пилет', 'а']",0,0,0,0,1,1
12,https://chitanka.info/book/648-prikazki.txt.zip,"— Ще опека, господарю — отвърнала Грета.","['ще', 'опека', 'господарю', 'отвърнала', 'гре...",5,"['ще', 'опека', 'господарю', 'отвърна', 'ла', ...",0,0,0,1,0,1
13,https://chitanka.info/book/648-prikazki.txt.zip,"Заклала тя пилетата, попарила ги, оскубала ги,...","['заклала', 'тя', 'пилетата', 'попарила', 'ги'...",20,"['закла', 'ла', 'тя', 'пилета', 'та', 'попари'...",1,0,0,1,1,1
14,https://chitanka.info/book/648-prikazki.txt.zip,Почнали пилетата да се зачервяват и да омекват...,"['почнали', 'пилетата', 'да', 'се', 'зачервява...",14,"['почна', 'ли', 'пилета', 'та', 'да', 'се', 'з...",1,0,0,1,1,1
15,https://chitanka.info/book/648-prikazki.txt.zip,Отишла Грета при господаря и му рекла:,"['отишла', 'грета', 'при', 'господаря', 'и', '...",7,"['отиш', 'ла', 'грета', 'при', 'господар', 'я'...",1,0,0,1,0,1
16,https://chitanka.info/book/648-prikazki.txt.zip,"— Ако гостът не дойде, ще трябва да сваля пиле...","['ако', 'гостът', 'не', 'дойде', 'ще', 'трябва...",11,"['ако', 'гост', 'ът', 'не', 'дойд', 'е', 'ще',...",1,0,0,0,1,1
17,https://chitanka.info/book/648-prikazki.txt.zip,"Жалко, че няма да бъдат изядени скоро, докато ...","['жалко', 'че', 'няма', 'да', 'бъдат', 'изяден...",12,"['жалко', 'че', 'няма', 'да', 'бъд', 'ат', 'из...",0,0,0,0,0,1
18,https://chitanka.info/book/648-prikazki.txt.zip,Господарят рекъл:,"['господарят', 'рекъл']",2,"['господар', 'ят', 'рекъ', 'л']",1,0,0,1,0,1
19,https://chitanka.info/book/648-prikazki.txt.zip,— Ще изтичам да доведа госта.,"['ще', 'изтичам', 'да', 'доведа', 'госта']",5,"['ще', 'изтичам', 'да', 'доведа', 'гос', 'та']",1,0,0,0,0,1
20,https://chitanka.info/book/648-prikazki.txt.zip,"Излязъл господарят, а Грета сложила настрана ш...","['излязъл', 'господарят', 'а', 'грета', 'сложи...",24,"['излязъл', 'господар', 'ят', 'а', 'грета', 'с...",1,0,0,1,1,1
21,https://chitanka.info/book/648-prikazki.txt.zip,Кой ги знае кога ще дойдат!,"['кой', 'ги', 'знае', 'кога', 'ще', 'дойдат']",6,"['кой', 'ги', 'зна', 'е', 'кога', 'ще', 'дойд'...",0,0,0,0,0,1
22,https://chitanka.info/book/648-prikazki.txt.zip,"Докато още ги няма, ще сляза в избата да пийна...","['докато', 'още', 'ги', 'няма', 'ще', 'сляза',...",12,"['докато', 'още', 'ги', 'няма', 'ще', 'сляза',...",1,0,0,0,0,1
23,https://chitanka.info/book/648-prikazki.txt.zip,"Изтичала по стълбата в избата, вдигнала една к...","['изтичала', 'по', 'стълбата', 'в', 'избата', ...",10,"['изтича', 'ла', 'по', 'стълба', 'та', 'в', 'и...",1,0,0,1,0,1
24,https://chitanka.info/book/648-prikazki.txt.zip,"— Наздраве, Грета!","['наздраве', 'грета']",2,"['наздраве', 'грета']",0,0,0,0,0,1

In [ ]:
df.size

612150

###Utils

In [ ]:
def save_sents(df, column_name, filepath):
  sents = [" ".join(literal_eval(u))+"\n" for u in df[column_name]]

  with open(filepath, mode="w") as f:
    f.writelines(sents)

### Save some sents for training

In [ ]:
# save_sents(df, "Tokenised", "drive/My Drive/Colab Notebooks/sents_normtok_bg_cds_copyrightsafe.raw" )

In [ ]:
save_sents(df, "MorphTok", "drive/My Drive/Colab Notebooks/sents_morphtok_bg_cds_copyrightsafe.raw" )

##Morph tok

In [ ]:
ARTICLE_SUFFIXES = ["ът", "ят", "та", "то", "те", "а", "я",]

def is_definite(token):
    #spaCy’s morphological analysis marks this token as definite
    return token.morph.get("Definite") == ["Def"]

def split_token(token):
    """
    Given a spaCy token, return a list of morpheme-tokens:
      - If not definite: [lowercased form], flag 0
      - If definite: [lemma, article_suffix], flag 1
    """
    if not is_definite(token):
        return [token.lower_], 0

    text = token.lower_
    lemma = token.lemma_.lower()
    # find which suffix matches
    for suffix in ARTICLE_SUFFIXES:
        if text.endswith(suffix):
            if lemma.endswith(suffix):
              lemma = lemma[:-len(suffix)]
            return [lemma, suffix], 1

    # fallback: no known suffix found, but morph says Definite
    # treat entire token as stem
    return [lemma], 1

def process_sentences(sents):
    """
    Process a list of raw sentences into:
      - sents_morphtok: list of lists of morpheme-tokens
      - definite_flags: flat list of 0/1 flags in token order
    """
    sents_morphtok = []
    definite_flags =[ ]

    for sent_text in sents:
        doc = nlp(sent_text)
        morphtok_sent = []
        sent_flag = 0
        for token in doc:
            if token.is_punct:
                continue
            morphemes, flag = split_token(token)
            morphtok_sent.extend(morphemes)
            if flag:
                sent_flag = 1
        definite_flags.append(sent_flag)
        sents_morphtok.append(morphtok_sent)

    return sents_morphtok, definite_flags

#### version using spacy morph

In [ ]:
ARTICLE_SUFFIXES = ["ът", "ят", "та", "то", "те", "а", "я"]
AORIST_SUFFIXES = ["х", "хме", "хте", "ха"]
IMPERFECT_SUFFIXES = ["х", "ше", "хме", "хте", "ха"]
PARTICIPLE_SUFFIXES = ["л", "ла", "ло", "ли"]
PRESENT_SING_SUFFIXES = ["а", "я", "еш", "иш", "е", "и"]
PRESENT_PLUR_SUFFIXES = ["ем", "им", "ете", "ите", "ат", "ят"]
NOUN_PLURAL_SUFFIXES = ["и", "ове", "е", "еве", "а", "ета"]

# Utilities
def ends_in_suffix(token, suffixes):
    text = token.lower_
    for suffix in sorted(suffixes, key=lambda s: -len(s)):
        if text.endswith(suffix) and len(text) > len(suffix):
            return suffix
    return None

# Feature Checkers
def is_definite(token):
    return token.morph.get("Definite") == ["Def"]

def is_aorist(token):
    return ends_in_suffix(token, AORIST_SUFFIXES) is not None

def is_imperfect(token):
    return ends_in_suffix(token, IMPERFECT_SUFFIXES) is not None

def is_participle(token):
    return ends_in_suffix(token, PARTICIPLE_SUFFIXES) is not None

def is_plural_noun(token):
    return "Number=Plur" in token.morph and token.pos_ == "NOUN"

def is_present(token):
    return ends_in_suffix(token, PRESENT_SING_SUFFIXES + PRESENT_PLUR_SUFFIXES) is not None

# Token Splitter
def split_token(token):
    text = token.lower_

    # Check each morpheme type
    if is_definite(token):
        suffix = ends_in_suffix(token, ARTICLE_SUFFIXES)
        if suffix:
            return [text[:-len(suffix)], suffix], 1

    for check_fn, suffixes in [
        (is_aorist, AORIST_SUFFIXES),
        (is_imperfect, IMPERFECT_SUFFIXES),
        (is_participle, PARTICIPLE_SUFFIXES),
        (is_present, PRESENT_SING_SUFFIXES + PRESENT_PLUR_SUFFIXES),
        (is_plural_noun, NOUN_PLURAL_SUFFIXES)
    ]:
        if check_fn(token):
            suffix = ends_in_suffix(token, suffixes)
            if suffix:
                return [text[:-len(suffix)], suffix], 1

    return [text], 0

# Sentence Processor
def process_sentences(sents):
    sents_morphtok = []
    definite_flags = []

    for sent_text in sents:
        doc = nlp(sent_text)
        morphtok_sent = []
        sent_flag = 0
        for token in doc:
            if token.is_punct:
                continue
            morphemes, flag = split_token(token)
            morphtok_sent.extend(morphemes)
            if flag:
                sent_flag = 1
        sents_morphtok.append(morphtok_sent)
        definite_flags.append(sent_flag)

    return sents_morphtok, definite_flags

####version using bg specific labels

In [ ]:
def is_definite(token):
    return token.morph.get("Definite") == ["Def"]

def is_imperfect(token):
    return token.tag_.startswith("V") and len(token.tag_) > 2 and token.tag_[2] == "i"

def is_aorist(token):
    return token.tag_.startswith("V") and len(token.tag_) > 2 and token.tag_[2] == "a"

def is_present(token):
    return token.tag_.startswith("V") and len(token.tag_) > 2 and token.tag_[2] == "t"

def is_participle(token):
    return token.tag_.startswith("V") and len(token.tag_) > 4 and token.tag_[4] == "p"

def is_plural_noun(token):
    return token.tag_.startswith("N") and len(token.tag_) > 7 and token.tag_[7] == "p"

def split_token(token):
    text = token.lower_
    lemma = token.lemma_.lower()

    # If lemma is in exclusion list, return as-is
    if lemma in EXCLUDED_LEMMAS:
        return [text], 0

    # Try definite article split
    if is_definite(token):
        suffix = ends_in_suffix(token, ARTICLE_SUFFIXES)
        if suffix:
            return [text[:-len(suffix)], suffix], 1

    # No suffix split for other morphs
    if any([
        is_imperfect(token),
        is_aorist(token),
        is_participle(token),
        is_present(token),
        is_plural_noun(token)
    ]):
        return [text], 1

    return [text], 0

def process_sentences(sents):
    morphtok_all = []
    def_flags = []
    aorist_flags = []
    imperfect_flags = []
    part_flags = []
    plur_flags = []
    pres_flags = []

    for sent_text in sents:
        doc = nlp(sent_text)
        tokens = [t for t in doc if not t.is_punct]
        morphtok_sent = []
        flags = {
            "def": 0, "aorist": 0, "imperfect": 0,
            "participle": 0, "plural": 0, "present": 0
        }

        for token in tokens:
            morphemes, _ = split_token(token)
            morphtok_sent.extend(morphemes)

            if is_definite(token): flags["def"] = 1
            if is_aorist(token): flags["aorist"] = 1
            if is_imperfect(token): flags["imperfect"] = 1
            if is_participle(token): flags["participle"] = 1
            if is_plural_noun(token): flags["plural"] = 1
            if is_present(token): flags["present"] = 1

        morphtok_all.append(morphtok_sent)
        def_flags.append(flags["def"])
        aorist_flags.append(flags["aorist"])
        imperfect_flags.append(flags["imperfect"])
        part_flags.append(flags["participle"])
        plur_flags.append(flags["plural"])
        pres_flags.append(flags["present"])

    return (
        morphtok_all, def_flags, aorist_flags,
        imperfect_flags, part_flags, plur_flags, pres_flags
    )

#### hacky version

In [ ]:
ARTICLE_SUFFIXES = ["ът", "ят", "та", "то",  "те", "а", "я"] # "ите","ия",
AORIST_SUFFIXES = ["х", "хме", "хте", "ха"]
IMPERFECT_SUFFIXES = ["х", "ше", "хме", "хте", "ха"]
PARTICIPLE_SUFFIXES = [ "ла", "ло", "ли", "л",]
PRESENT_SING_SUFFIXES = [ "еш", "иш", "е", "и", "а", "я",]
PRESENT_PLUR_SUFFIXES = ["ме", "ем", "им", "ете", "ите", "ат", "ят", ]
NOUN_PLURAL_SUFFIXES = ["ове", "еве", "ета", "а","е", "и",]

# Utilities
def ends_in_suffix(token, suffixes):
    text = token.lower_
    for suffix in suffixes:
    # for suffix in sorted(suffixes, key=lambda s: -len(s)):
        if text.endswith(suffix) and len(text) > len(suffix):
            return suffix
    return None

# Feature Checkers
def is_definite(token):
    return token.morph.get("Definite") == ["Def"]

def is_aorist(token):
    return ends_in_suffix(token, AORIST_SUFFIXES) is not None

def is_imperfect(token):
    return ends_in_suffix(token, IMPERFECT_SUFFIXES) is not None

def is_participle(token):
    return ends_in_suffix(token, PARTICIPLE_SUFFIXES) is not None

def is_plural_noun(token):
    return "Number=Plur" in token.morph and token.pos_ == "NOUN"

def is_present(token):
    return ends_in_suffix(token, PRESENT_SING_SUFFIXES + PRESENT_PLUR_SUFFIXES) is not None

def is_nouny(token):
      return token.pos_ in {"NOUN", "ADJ", "PROPN", "PRON"}


# Token Splitter
def split_token(token):
    text = token.lower_
    lemma = token.lemma_.lower()

    # If lemma is in exclusion list, return as-is
    if text in EXCLUDED_LEMMAS:
        # print("in here")
        return [text], 0

    # Check each morpheme type
    if is_definite(token) or is_nouny(token):
        suffix = ends_in_suffix(token, ARTICLE_SUFFIXES)
        # print(token, suffix)
        if suffix:
            return [text[:-len(suffix)], suffix], 1

    for check_fn, suffixes in [
        (is_aorist, AORIST_SUFFIXES),
        (is_imperfect, IMPERFECT_SUFFIXES),
        (is_participle, PARTICIPLE_SUFFIXES),
        (is_present, PRESENT_PLUR_SUFFIXES + PRESENT_SING_SUFFIXES ),
        (is_plural_noun, NOUN_PLURAL_SUFFIXES)
    ]:
        if check_fn(token):
            suffix = ends_in_suffix(token, suffixes)
            if suffix:
                return [text[:-len(suffix)], suffix], 1

    return [text], 0

def process_sentence(sent_text):
    """
    Process a single sentence and return:
    - morpheme-tokenized list
    - flags for morph categories
    """
    flags = {
        "def": 0, "aorist": 0, "imperfect": 0,
        "participle": 0, "plural": 0, "present": 0
    }
    morphtok_sent = []
    doc = nlp(sent_text)

    for token in doc:
        if token.is_punct:
            continue
        morphemes, _ = split_token(token)
        morphtok_sent.extend(morphemes)

        if is_definite(token): flags["def"] = 1
        if is_aorist(token): flags["aorist"] = 1
        if is_imperfect(token): flags["imperfect"] = 1
        if is_participle(token): flags["participle"] = 1
        if is_plural_noun(token): flags["plural"] = 1
        if is_present(token): flags["present"] = 1

    return morphtok_sent, flags
def process_sentences(sents):
    """
    Process a list of sentences using `process_sentence`
    """
    sents_morphtok = []
    def_flags = []
    aorist_flags = []
    imperfect_flags = []
    part_flags = []
    plur_flags = []
    pres_flags = []

    for sent_text in sents:
        morphtok_sent, flags = process_sentence(sent_text)

        sents_morphtok.append(morphtok_sent)
        def_flags.append(flags["def"])
        aorist_flags.append(flags["aorist"])
        imperfect_flags.append(flags["imperfect"])
        part_flags.append(flags["participle"])
        plur_flags.append(flags["plural"])
        pres_flags.append(flags["present"])

    return (
        sents_morphtok, def_flags, aorist_flags,
        imperfect_flags, part_flags, plur_flags, pres_flags
    )

In [ ]:
# assert(is_definite(nlp(test_sents[0])[1]))
# assert(not is_definite(nlp(test_sents[0])[2]))

test_sents = [
    "Виждахме мечката и кучето в градината.",  # imperfect: "виждахме", article: "мечката"
    "Те говориха много.",                      # aorist: "говориха"
    "Децата играят в парка.",                  # plural article: "децата", verb: "играят"
    "Бях гледал филма.",                       # participle: "гледал"
    "Умницата Грета",                          # article: "умницата"
    "Котките са жълти.",                        # definite (plural)
    "По-хубаво е в София.",                     # comparative
    "по-хубаво",
    "ядрената"
]

process_sentences(test_sents)

([['вижда', 'хме', 'мечка', 'та', 'и', 'куче', 'то', 'в', 'градина', 'та'],
  ['те', 'говори', 'ха', 'много'],
  ['деца', 'та', 'игра', 'ят', 'в', 'парка'],
  ['бя', 'х', 'гледа', 'л', 'филм', 'а'],
  ['умница', 'та', 'грета'],
  ['котки', 'те', 'с', 'а', 'жълти'],
  ['по', 'хубаво', 'е', 'в', 'софия'],
  ['по', 'хубаво'],
  ['ядрена', 'та']],
 [1, 0, 1, 1, 1, 1, 0, 0, 1],
 [1, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 0, 1])

In [ ]:
(
    df["MorphTok"], df["def"], df["aorist"],
    df["imperfect"], df["participle"], df["plural"], df["present"]
) = process_sentences(df["Utterance"].tolist())

KeyboardInterrupt:

In [ ]:
# sents_morphtok, definite = process_sentences(df.Utterance.tolist())
# df["MorphTok"] = sents_morphtok
# df["def"] = definite

In [ ]:
df.to_csv(r'drive/My Drive/Colab Notebooks/bg_cds_copyrightsafe.csv', index=False)

In [ ]:
df.MorphTok.tolist()

###BG Morphemes

In [ ]:
# Aorist (Минало свършено време)
aorist_endings = [
    "-х",   # 1 л. ед.ч.
    "",     # 2 л. ед.ч.
    "",     # 3 л. ед.ч.
    "-хме", # 1 л. мн.ч.
    "-хте", # 2 л. мн.ч.
    "-ха"   # 3 л. мн.ч.
]

# Imperfect (Минало несвършено време)
imperfect_endings = [
    "-х",   # 1 л. ед.ч.
    "-ше",  # 2 л. ед.ч.
    "-ше",  # 3 л. ед.ч.
    "-хме", # 1 л. мн.ч.
    "-хте", # 2 л. мн.ч.
    "-ха"   # 3 л. мн.ч.
]

# Perfect (Минало неопределено време)
# Each entry is a tuple: (masc, fem, plural)
participle_endings = ["-л", "-ла", "-ло", "-ли"]

plural_noun_endings = {
    "masculine": {
        "hard consonant": ["-и", "-ове", "-е"],
        "soft consonant (й, ч, ш)": ["-еве", "-ове", "-и"]
    },
    "feminine": {
        "ends in -а / -я": ["-и"],
        "ends in consonant": ["-и", "-ове"]
    },
    "neuter": {
        "ends in -о / -е": ["-а", "-ета"],
        "ends in stressed -е": ["-ета"]
    }
}

# Singular endings for present tense
present_singular_endings = [
    "-а", "-я",       # 1st person singular
    "-еш", "-иш",     # 2nd person singular
    "-е", "-и"        # 3rd person singular
]

# Plural endings for present tense
present_plural_endings = [
    "-ем", "-им",             # 1st person plural
    "-ете", "-ите",           # 2nd person plural
    "-ат", "-ят"              # 3rd person plural
]

###Exceptions

In [ ]:
import requests
import gzip
import io
from urllib.parse import unquote


SITEMAP_URLS = [
    "http://rechnik.chitanka.info/sitemaps/word.1.txt.gz",
    "http://rechnik.chitanka.info/sitemaps/word.2.txt.gz",
    "http://rechnik.chitanka.info/sitemaps/word.3.txt.gz",
]

EXCLUDED_LEMMAS = []

for url in SITEMAP_URLS:
    print(f"Downloading: {url}")
    response = requests.get(url)
    with gzip.open(io.BytesIO(response.content), 'rt', encoding='utf-8') as f:
        for line in f:
            EXCLUDED_LEMMAS.append(line.strip())

# Save to file (optional)
# with open("lemmas.txt", "w", encoding="utf-8") as out:
#     for lemma_url in EXCLUDED_LEMMAS:
#         out.write(lemma_url + "\n")

print(f"Extracted {len(EXCLUDED_LEMMAS)} lemmas.")

EXCLUDED_LEMMAS = [unquote(url.split("/w/")[1]) for url in EXCLUDED_LEMMAS]
EXCLUDED_LEMMAS = [e.lower() for e in EXCLUDED_LEMMAS]
EXCLUDED_LEMMAS = set(EXCLUDED_LEMMAS)

Downloading: http://rechnik.chitanka.info/sitemaps/word.1.txt.gz
Downloading: http://rechnik.chitanka.info/sitemaps/word.2.txt.gz
Downloading: http://rechnik.chitanka.info/sitemaps/word.3.txt.gz
Extracted 117871 lemmas.

words that end in та

In [ ]:
endings = {}

In [ ]:
w_ta = [w for w in words if w.endswith("та")]

NameError: name 'words' is not defined

In [ ]:
w_i = [w for w in words if w.endswith("и")]

In [ ]:
for s in nlp("Вървях си под моста и гледам в дола момиченце малко печеше цаца. Четох, че рибите са сини. Чиниите ръмжаха силно. Виждахме мечката и кучето в градината. Те говориха много. Децата играят в парка. Бях гледал филма. Умницата Грета. ").sents:
  print('\n')
  for t in s:
    if t.pos_ != "PUNCT":
      print(t.lower_, t.lemma_, t.pos_, t.tag_, t.morph) #doesn't have: t.lex_, t.morph_

## MorphScore

#### score for bg is 0.584 from https://aclanthology.org/2025.coling-main.441.pdf and

In [ ]:
# --- Step 1: Imports ---
import pandas as pd
import numpy as np
import requests
import io

# --- Step 2: Load Bulgarian MorphScore Data from GitHub ---
url = "https://github.com/catherinearnett/morphscore/raw/v1/data/bulgarian_morph_data.csv"
csv_data = requests.get(url).content
morph_data = pd.read_csv(io.StringIO(csv_data.decode("utf-8")))

# --- Step 3: MorphScore Evaluation Logic ---
def morph_eval(morphemes, tokens):  # returns -1, 0, 1
    if len(tokens) == 1:
        return 0
    for t in range(len(tokens)-1):
        pt1 = ''.join(tokens[:t+1])
        rest = ''.join(tokens[t+1:])
        if [pt1, rest] == morphemes:
            return 1
    return -1

def get_morphscore(data, tokenizer):
    points = []
    error_rows = []

    for _, row in data.iterrows():
        morphemes = [row['pt1'], row['rest']]
        word = row['full_word']
        tokens = tokenizer(word)

        point = morph_eval(morphemes, tokens)

        # Only score cases with a segmentation attempt
        if point != 0:
            points.append(0 if point == -1 else 1)

        # Collect error info if incorrect
        if point == -1:
            error_rows.append({
                "full_word": word,
                "gold": morphemes,
                "predicted": tokens,
                "result": "wrong"
            })
        elif point == 1:
            error_rows.append({
                "full_word": word,
                "gold": morphemes,
                "predicted": tokens,
                "result": "correct"
            })

    morph_score = np.mean(points) if points else 0.0
    error_df = pd.DataFrame(error_rows)
    return morph_score, error_df

In [ ]:
def my_tokenizer(sentence):
    morphemes, _ = process_sentence(sentence)
    return morphemes

# Now use it with get_morphscore
score, errors_df = get_morphscore(morph_data, my_tokenizer)

print("MorphScore:", round(score, 4))
display(errors_df)  # If using Jupyter

MorphScore: 0.6996

           full_word                gold            predicted   result
0            вятърът         [вятър, ът]          [вятър, ът]  correct
1           ураганът        [ураган, ът]         [ураган, ът]  correct
2     посланическите  [посланически, те]   [посланически, те]  correct
3            затвора         [затвор, а]          [затвор, а]  correct
4            приемат         [приема, т]          [прием, ат]    wrong
...              ...                 ...                  ...      ...
1899  топлофикацията  [топлофикация, та]   [топлофикация, та]  correct
1900           целта           [цел, та]            [цел, та]  correct
1901       брокерите       [брокер, ите]        [брокери, те]    wrong
1902       русалката       [русалка, та]        [русалка, та]  correct
1903  уеб-страницата  [уеб-страница, та]  [уеб, страница, та]    wrong

[1904 rows x 4 columns]

In [ ]:
errors_df[errors_df.result=="wrong"].head(50)

,full_word,gold,predicted,result
4,приемат,"[приема, т]","[прием, ат]",wrong
14,ядрената,"[ядрен, ата]","[ядрена, та]",wrong
17,изборите,"[избор, ите]","[избори, те]",wrong
24,нарядите,"[наряд, ите]","[наряди, те]",wrong
26,широките,"[широк, ите]","[широки, те]",wrong
27,черните,"[чер, ните]","[черни, те]",wrong
29,веселата,"[весел, ата]","[весела, та]",wrong
35,страдаме,"[страдам, е]","[страда, ме]",wrong
41,респондентите,"[респондент, ите]","[респонденти, те]",wrong
42,спринта,"[спринт, а]","[сприн, та]",wrong
44,по-добър,"[по-, добър]","[по, добър]",wrong
48,милите,"[мил, ите]","[мили, те]",wrong
53,висшестоящия,"[висшестоящ, ия]","[висшестоящи, я]",wrong
54,по-малък,"[по-, малък]","[по, малък]",wrong
56,изберат,"[избера, т]","[избер, ат]",wrong
58,хубавото,"[хубав, ото]","[хубаво, то]",wrong
59,акционерите,"[акционер, ите]","[акционери, те]",wrong
63,помощник-треньорът,"[помощник-треньор, ът]","[помощник, треньор, ът]",wrong
64,ексшампионите,"[ексшампион, ите]","[ексшампиони, те]",wrong
72,тежат,"[тежа, т]","[теж, ат]",wrong
77,трудностите,"[трудност, ите]","[трудности, те]",wrong
84,посещаваме,"[посещавам, е]","[посещава, ме]",wrong
85,месопреработвателите,"[месопреработвател, ите]","[месопреработватели, те]",wrong
87,инспектората,"[инспекторат, а]","[инспектора, та]",wrong
88,пеленачетата,"[пеленаче, тата]","[пеленачета, та]",wrong
89,помогнат,"[помогна, т]","[помогн, ат]",wrong
90,високата,"[висок, ата]","[висока, та]",wrong
95,имуществените,"[имуществен, ите]","[имуществени, те]",wrong
104,успехите,"[успех, ите]","[успехи, те]",wrong
106,поста,"[пост, а]","[пос, та]",wrong
109,левскарите,"[левскар, ите]","[левскари, те]",wrong
110,посетят,"[посетя, т]","[посет, ят]",wrong
111,кореспондента,"[кореспондент, а]","[кореспонден, та]",wrong
119,по-ясно,"[по-, ясно]","[по, ясно]",wrong
121,Най-слабо,"[Най-, слабо]","[най, слабо]",wrong
125,по-близко,"[по-, близко]","[по, близко]",wrong
126,избягаме,"[избягам, е]","[избяга, ме]",wrong
129,следствените,"[следствен, ите]","[следствени, те]",wrong
134,Най-тежък,"[Най-, тежък]","[най, тежък]",wrong
140,културно-историческите,"[културно-исторически, те]","[културно, исторически, те]",wrong
151,заглъхналия,"[заглъхна, лия]","[заглъхнали, я]",wrong
153,заболеят,"[заболея, т]","[заболе, ят]",wrong
159,великите,"[велик, ите]","[велики, те]",wrong
163,смахнатият,"[смахнат, ият]","[смахнати, ят]",wrong
164,дебитите,"[дебит, ите]","[дебити, те]",wrong
167,Най-голям,"[Най-, голям]","[най, голям]",wrong
168,кралете,"[крал, ете]","[крале, те]",wrong
174,нашите,"[наш, ите]","[наши, те]",wrong
176,адвокатите,"[адвокат, ите]","[адвокати, те]",wrong
180,неоспоримата,"[неоспорим, ата]","[неоспорима, та]",wrong

### Discarded: getting lemmas from the BTB, but they are not actually all lemmas and only 14K

In [ ]:
import os
import requests
import zipfile

# Step 1: Download and unzip UD Bulgarian-BTB dataset
url = "https://github.com/UniversalDependencies/UD_Bulgarian-BTB/archive/refs/tags/r2.12.zip"
zip_path = "bg_btb.zip"

print("⬇️ Downloading UD Bulgarian Treebank...")
r = requests.get(url)
with open(zip_path, "wb") as f:
    f.write(r.content)

print("🗂️ Extracting...")
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(".")

base_folder = "UD_Bulgarian-BTB-r2.12"
conllu_files = [
    "bg_btb-ud-train.conllu",
    "bg_btb-ud-dev.conllu",
    "bg_btb-ud-test.conllu"
]

# Step 2: Parse lemmas
lemmas = set()

for file in conllu_files:
    path = os.path.join(base_folder, file)
    with open(path, encoding="utf-8") as f:
        for line in f:
            print(line)
            if line.strip() and not line.startswith("#"):
                fields = line.split("\t")
                if len(fields) >= 3:
                    lemma = fields[2]
                    if lemma != "_":
                        lemmas.add(lemma)

print(f"✅ Extracted {len(lemmas)} unique lemmas")

# Step 3: Save lemmas to file
lemmas_file = "bulgarian_lemmas.txt"
with open(lemmas_file, "w", encoding="utf-8") as f:
    for lemma in sorted(lemmas):
        f.write(lemma + "\n")

print(f"📁 Lemmas saved to {lemmas_file}")

Streaming output truncated to the last 5000 lines.
# text = Глобата за продажба на алкохол и цигари без лиценз е 15000 лв.

1	Глобата	глоба	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	12	nsubj	12:nsubj	_

2	за	за	ADP	R	_	3	case	3:case	_

3	продажба	продажба	NOUN	Ncfsi	Definite=Ind|Gender=Fem|Number=Sing	1	nmod	1:nmod:за	_

4	на	на	ADP	R	_	5	case	5:case	_

5	алкохол	алкохол	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	3	nmod	3:nmod:на	_

6	и	и	CCONJ	Cp	_	7	cc	7:cc	_

7	цигари	цигара	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	5	conj	5:conj	_

8	без	без	ADP	R	_	9	case	9:case	_

9	лиценз	лиценз	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	3	nmod	3:nmod:без	_

10	е	съм	AUX	Vxitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	12	cop	12:cop	_

11	15000	15000	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	12	nummod	12:nummod	_

12	лв.	лев	NOUN	Ncmt	Gender=Masc|Number=Count	0	root	0:root	_



# sent_id = Standard-2000-10-24-s200

# text = Премиерът обяви радикален завой в приватизацията, РМД-та няма да се допускат до продажбата на монополите

1	Премиерът	премиер	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	2	nsubj	2:nsubj	_

2	обяви	обявя-(се)	VERB	Vpptf-o3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|Voice=Act	0	root	0:root	_

3	радикален	радикален	ADJ	Amsi	Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing	4	amod	4:amod	_

4	завой	завой	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	2	obj	2:obj	_

5	в	в	ADP	R	_	6	case	6:case	_

6	приватизацията	приватизация	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	4	nmod	4:nmod:в	SpaceAfter=No

7	,	,	PUNCT	punct	_	9	punct	9:punct	_

8	РМД-та	рмд-та	PROPN	Npnpi	Definite=Ind|Gender=Neut|Number=Plur	12	nsubj:pass	12:nsubj:pass	_

9	няма	нямам	VERB	Vnitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	4	acl	4:acl	_

10	да	да	AUX	Tx	_	12	aux	12:aux	_

11	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	12	expl	12:expl	_

12	допускат	допускам	VERB	Vpitf-r3p	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	9	ccomp	9:ccomp	_

13	до	до	ADP	R	_	14	case	14:case	_

14	продажбата	продажба	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	12	iobj	12:iobj	_

15	на	на	ADP	R	_	16	case	16:case	_

16	монополите	монопол	NOUN	Ncmpd	Definite=Def|Gender=Masc|Number=Plur	14	nmod	14:nmod:на	_



# sent_id = Standard-2000-10-24-s212

# text = Съветът ще дава задължителни указания за всички етапи на подготовка на дадена сделка и становище по приватизационните договори, които се сключват от министерствата.

1	Съветът	съвет	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	3	nsubj	3:nsubj	_

2	ще	ще	AUX	Tx	_	3	aux	3:aux	_

3	дава	давам-(се)	VERB	Vpitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_

4	задължителни	задължителен	ADJ	A-pi	Definite=Ind|Degree=Pos|Number=Plur	5	amod	5:amod	_

5	указания	указание	NOUN	Ncnpi	Definite=Ind|Gender=Neut|Number=Plur	3	obj	3:obj	_

6	за	за	ADP	R	_	8	case	8:case	_

7	всички	всеки	DET	Pce-op	Case=Nom|Number=Plur|PronType=Tot	8	det	8:det	_

8	етапи	етап	NOUN	Ncmpi	Definite=Ind|Gender=Masc|Number=Plur	5	nmod	5:nmod:за	_

9	на	на	ADP	R	_	10	case	10:case	_

10	подготовка	подготовка	NOUN	Ncfsi	Definite=Ind|Gender=Fem|Number=Sing	8	nmod	8:nmod:на	_

11	на	на	ADP	R	_	13	case	13:case	_

12	дадена	даден	ADJ	Afsi	Definite=Ind|Degree=Pos|Gender=Fem|Number=Sing	13	amod	13:amod	_

13	сделка	сделка	NOUN	Ncfsi	Definite=Ind|Gender=Fem|Number=Sing	10	nmod	10:nmod:на	_

14	и	и	CCONJ	Cp	_	15	cc	15:cc	_

15	становище	становище	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	5	conj	3:obj|5:conj	_

16	по	по	ADP	R	_	18	case	18:case	_

17	приватизационните	приватизационен	ADJ	A-pd	Definite=Def|Degree=Pos|Number=Plur	18	amod	18:amod	_

18	договори	договор	NOUN	Ncmpi	Definite=Ind|Gender=Masc|Number=Plur	15	nmod	15:nmod:по|22:nsubj:pass	SpaceAfter=No

19	,	,	PUNCT	punct	_	22	punct	22:punct	_

20	които	който	PRON	Pre-op	Case=Nom|Number=Plur|PronType=Rel	22	nsubj:pass	18:ref	_

21	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	22	expl	22:expl	_

22	сключват	сключвам	VERB	Vpitf-r3p	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	18	acl:relcl	18:acl:relcl	_

23	от	от	ADP	R	_	24	case	24:case	_

24	министерствата	министерство	NOUN	Ncnpd	Definite=Def|Gender=Neut|Number=Plur	22	iobj	22:iobj	SpaceAfter=No

25	.	.	PUNCT	punct	_	3	punct	3:punct	_



# sent_id = Standard-2000-10-24-s224

# text = Приватизацията на предприятията монополисти ще се прави според разработена от правителството стратегия, която ще се одобрява от парламента.

1	Приватизацията	приватизация	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	7	nsubj:pass	7:nsubj:pass	_

2	на	на	ADP	R	_	3	case	3:case	_

3	предприятията	предприятие	NOUN	Ncnpd	Definite=Def|Gender=Neut|Number=Plur	1	nmod	1:nmod:на	_

4	монополисти	монополист	NOUN	Ncmpi	Definite=Ind|Gender=Masc|Number=Plur	3	nmod	3:nmod	_

5	ще	ще	AUX	Tx	_	7	aux	7:aux	_

6	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	7	expl	7:expl	_

7	прави	правя-(се)	VERB	Vpitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_

8	според	според	ADP	R	_	12	case	12:case	_

9	разработена	разработя-(се)	ADJ	Vpptcv--sfi	Aspect=Perf|Definite=Ind|Degree=Pos|Gender=Fem|Number=Sing|VerbForm=Part|Voice=Pass	12	amod	12:amod	_

10	от	от	ADP	R	_	11	case	11:case	_

11	правителството	правителство	NOUN	Ncnsd	Definite=Def|Gender=Neut|Number=Sing	9	obl	9:obl:от	_

12	стратегия	стратегия	NOUN	Ncfsi	Definite=Ind|Gender=Fem|Number=Sing	7	obl	7:obl:според|17:nsubj:pass	SpaceAfter=No

13	,	,	PUNCT	punct	_	17	punct	17:punct	_

14	която	който	PRON	Pre-os-f	Case=Nom|Gender=Fem|Number=Sing|PronType=Rel	17	nsubj:pass	12:ref	_

15	ще	ще	AUX	Tx	_	17	aux	17:aux	_

16	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	17	expl	17:expl	_

17	одобрява	одобрявам	VERB	Vpitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	12	acl:relcl	12:acl:relcl	_

18	от	от	ADP	R	_	19	case	19:case	_

19	парламента	парламент	NOUN	Ncmsh	Definite=Def|Gender=Masc|Number=Sing	17	iobj	17:iobj	SpaceAfter=No

20	.	.	PUNCT	punct	_	7	punct	7:punct	_



# sent_id = Standard-2000-10-24-s236

# text = Най-вероятно Желязков ще потърси от Министерство на икономиката съдействие за увеличаване на продавания държавен дял от фирмата.

1	Най-вероятно	вероятно	ADV	Dd	Degree=Sup	4	advmod	4:advmod	_

2	Желязков	желязков	PROPN	Hmsi	Definite=Ind|Gender=Masc|Number=Sing	4	nsubj	4:nsubj	_

3	ще	ще	AUX	Tx	_	4	aux	4:aux	_

4	потърси	потърся	VERB	Vpptf-r3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_

5	от	от	ADP	R	_	6	case	6:case	_

6	Министерство	министерство	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	9	nmod	9:nmod:от	_

7	на	на	ADP	R	_	8	case	8:case	_

8	икономиката	икономика	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	6	nmod	6:nmod:на	_

9	съдействие	съдействие	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	4	obj	4:obj	_

10	за	за	ADP	R	_	11	case	11:case	_

11	увеличаване	увеличаване	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	9	nmod	9:nmod:за	_

12	на	на	ADP	R	_	15	case	15:case	_

13	продавания	продавам	ADJ	Vpitcv--smh	Aspect=Imp|Definite=Def|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass	15	amod	15:amod	_

14	държавен	държавен	ADJ	Amsi	Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing	15	amod	15:amod	_

15	дял	дял	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	11	nmod	11:nmod:на	_

16	от	от	ADP	R	_	17	case	17:case	_

17	фирмата	фирма	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	15	nmod	15:nmod:от	SpaceAfter=No

18	.	.	PUNCT	punct	_	4	punct	4:punct	_



# sent_id = Standard-2000-10-24-s257

# text = Докато Шейтанов не бъде допуснат до материалите, няма смисъл да пътува за Либия, отвърна Антоанета Узунова в отговор на репортерски въпрос дали адвокатът ще замине за делото на 4 ноември.

1	Докато	докато	SCONJ	Cs	_	5	mark	5:mark	_

2	Шейтанов	шейтанов	PROPN	Hmsi	Definite=Ind|Gender=Masc|Number=Sing	5	nsubj:pass	5:nsubj:pass|12:nsubj	_

3	не	не	PART	Tn	Polarity=Neg	5	advmod	5:advmod	_

4	бъде	бъда	AUX	Vyptf-r3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	5	aux	5:aux	_

5	допуснат	допусна	VERB	Vpptcv--smi	Aspect=Perf|Definite=Ind|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass	9	advcl	9:advcl:докато	_

6	до	до	ADP	R	_	7	case	7:case	_

7	материалите	материал	NOUN	Ncmpd	Definite=Def|Gender=Masc|Number=Plur	5	iobj	5:iobj	SpaceAfter=No

8	,	,	PUNCT	punct	_	5	punct	5:punct	_

9	няма	нямам	VERB	Vnitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	16	ccomp	16:ccomp	_

10	смисъл	смисъл	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	9	obj	9:obj	_

11	да	да	AUX	Tx	_	12	aux	12:aux	_

12	пътува	пътувам	VERB	Vpiif-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	10	acl	10:acl	_

13	за	за	ADP	R	_	14	case	14:case	_

14	Либия	либия	PROPN	Npfsi	Definite=Ind|Gender=Fem|Number=Sing	12	iobj	12:iobj	SpaceAfter=No

15	,	,	PUNCT	punct	_	9	punct	9:punct	_

16	отвърна	отвърна-(се)	VERB	Vpptf-o3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|Voice=Act	0	root	0:root	_

17	Антоанета	антоанета	PROPN	Npfsi	Definite=Ind|Gender=Fem|Number=Sing	16	nsubj	16:nsubj	_

18	Узунова	узунова	PROPN	Hfsi	Definite=Ind|Gender=Fem|Number=Sing	17	flat	17:flat	_

19	в	в	ADP	R	_	20	case	20:case	_

20	отговор	отговор	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	16	obl	16:obl:в	_

21	на	на	ADP	R	_	23	case	23:case	_

22	репортерски	репортерски	ADJ	Amsi	Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing	23	amod	23:amod	_

23	въпрос	въпрос	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	20	nmod	20:nmod:на	_

24	дали	дали	PART	Ti	_	27	discourse	27:discourse	_

25	адвокатът	адвокат	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	27	nsubj	12:nsubj|27:nsubj	_

26	ще	ще	AUX	Tx	_	27	aux	27:aux	_

27	замине	замина	VERB	Vpptf-r3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	23	acl	23:acl	_

28	за	за	ADP	R	_	29	case	29:case	_

29	делото	дело	NOUN	Ncnsd	Definite=Def|Gender=Neut|Number=Sing	27	iobj	27:iobj	_

30	на	на	ADP	R	_	32	case	32:case	_

31	4	четвърти	ADJ	Momsi	Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing|NumType=Ord	32	amod	32:amod	_

32	ноември	ноември	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	29	nmod	29:nmod:на	SpaceAfter=No

33	.	.	PUNCT	punct	_	16	punct	16:punct	_



# sent_id = Standard-2000-10-24-s273

# text = Искаме да върнем доверието

1	Искаме	искам	VERB	Vpitf-r1p	Aspect=Imp|Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_

2	да	да	AUX	Tx	_	3	aux	3:aux	_

3	върнем	върна-(се)	VERB	Vpptf-r1p	Aspect=Perf|Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin|Voice=Act	1	csubj	1:csubj	_

4	доверието	доверие	NOUN	Ncnsd	Definite=Def|Gender=Neut|Number=Sing	3	obj	3:obj	_



# sent_id = Standard-2000-10-24-s287

# text = Купувачът трябва да плати за завода сумата от $ 550 хил. на 9 вноски за 10 години, като 10 % от цената се плаща в деня на подписване на сделката.

1	Купувачът	купувач	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	4	nsubj	4:nsubj	_

2	трябва	трябва	VERB	Vniif-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	0	root	0:root	_

3	да	да	AUX	Tx	_	4	aux	4:aux	_

4	плати	платя	VERB	Vpptf-r3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	2	ccomp	2:ccomp	_

5	за	за	ADP	R	_	6	case	6:case	_

6	завода	завод	NOUN	Ncmsh	Definite=Def|Gender=Masc|Number=Sing	4	obl	4:obl:за	_

7	сумата	сума	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	4	obj	4:obj	_

8	от	от	ADP	R	_	9	case	9:case	_

9	$	долар	NOUN	Ncmt	Gender=Masc|Number=Count	7	nmod	7:nmod:от	_

10	550	550	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	11	nummod	11:nummod	_

11	хил.	хиляда	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	9	nmod	9:nmod	_

12	на	на	ADP	R	_	14	case	14:case	_

13	9	девет	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	14	nummod	14:nummod	_

14	вноски	вноска	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	4	obl	4:obl:на	_

15	за	за	ADP	R	_	17	case	17:case	_

16	10	10	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	17	nummod	17:nummod	_

17	години	година	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	4	obl	4:obl:за	SpaceAfter=No

18	,	,	PUNCT	punct	_	25	punct	25:punct	_

19	като	като	SCONJ	Cs	_	25	mark	25:mark	_

20	10	10	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	21	nummod	21:nummod	_

21	%	процент	NOUN	Ncmt	Gender=Masc|Number=Count	25	nsubj:pass	25:nsubj:pass	_

22	от	от	ADP	R	_	23	case	23:case	_

23	цената	цена	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	21	nmod	21:nmod:от	_

24	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	25	expl	25:expl	_

25	плаща	плащам	VERB	Vpitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	4	advcl	4:advcl:като	_

26	в	в	ADP	R	_	27	case	27:case	_

27	деня	ден	NOUN	Ncmsh	Definite=Def|Gender=Masc|Number=Sing	25	obl	25:obl:в	_

28	на	на	ADP	R	_	29	case	29:case	_

29	подписване	подписване	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	27	nmod	27:nmod:на	_

30	на	на	ADP	R	_	31	case	31:case	_

31	сделката	сделка	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	29	nmod	29:nmod:на	SpaceAfter=No

32	.	.	PUNCT	punct	_	2	punct	2:punct	_



# sent_id = Standard-2000-10-24-s288

# text = Размерът на обещаните инвестиции е 580 хил. лева за 5 години.

1	Размерът	размер	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	7	nsubj	7:nsubj	_

2	на	на	ADP	R	_	4	case	4:case	_

3	обещаните	обещая	ADJ	Vpptcv--p-d	Aspect=Perf|Definite=Def|Degree=Pos|Number=Plur|VerbForm=Part|Voice=Pass	4	amod	4:amod	_

4	инвестиции	инвестиция	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	1	nmod	1:nmod:на	_

5	е	съм	AUX	Vxitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	7	cop	7:cop	_

6	580	580	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	7	nummod	7:nummod	_

7	хил.	хиляда	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	0	root	0:root	_

8	лева	лев	NOUN	Ncmt	Gender=Masc|Number=Count	7	nmod	7:nmod	_

9	за	за	ADP	R	_	11	case	11:case	_

10	5	5	NUM	Mc-pi	Definite=Ind|Number=Plur|NumType=Card	11	nummod	11:nummod	_

11	години	година	NOUN	Ncfpi	Definite=Ind|Gender=Fem|Number=Plur	7	nmod	7:nmod:за	SpaceAfter=No

12	.	.	PUNCT	punct	_	7	punct	7:punct	_



# sent_id = Standard-2000-10-24-s299

# text = Там лекарите открили заболяването, но нямали възможност да извършат операцията.

1	Там	там	ADV	Pdl	PronType=Dem	3	advmod	3:advmod	_

2	лекарите	лекар	NOUN	Ncmpd	Definite=Def|Gender=Masc|Number=Plur	3	nsubj	3:nsubj|7:nsubj|10:nsubj	_

3	открили	открия-(се)	VERB	Vpptcao-p-i	Aspect=Perf|Definite=Ind|Number=Plur|Tense=Past|VerbForm=Part|Voice=Act	0	root	0:root	_

4	заболяването	заболяване	NOUN	Ncnsd	Definite=Def|Gender=Neut|Number=Sing	3	obj	3:obj	SpaceAfter=No

5	,	,	PUNCT	punct	_	6	punct	6:punct	_

6	но	но	CCONJ	Cc	_	7	cc	7:cc	_

7	нямали	нямам	VERB	Vpitcao-p-i	Aspect=Imp|Definite=Ind|Number=Plur|Tense=Past|VerbForm=Part|Voice=Act	3	conj	3:conj	_

8	възможност	възможност	NOUN	Ncfsi	Definite=Ind|Gender=Fem|Number=Sing	7	obj	7:obj	_

9	да	да	AUX	Tx	_	10	aux	10:aux	_

10	извършат	извърша	VERB	Vpptf-r3p	Aspect=Perf|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	8	acl	8:acl	_

11	операцията	операция	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	10	obj	10:obj	SpaceAfter=No

12	.	.	PUNCT	punct	_	3	punct	3:punct	_



# sent_id = Standard-2000-10-24-s310

# text = Това стана ясно по време на вчерашното заседание по делото срещу шефа на пирамидата "Лайф чойс".

1	Това	този	PRON	Pde-os-n	Case=Nom|Gender=Neut|Number=Sing|PronType=Dem	2	nsubj	2:nsubj	_

2	стана	стане	VERB	Vnpif-o3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|Voice=Act	0	root	0:root	_

3	ясно	ясен	ADJ	Ansi	Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing	2	obj	2:obj	_

4	по	по	ADP	R	_	5	case	5:case	_

5	време	време	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	2	obl	2:obl:по	_

6	на	на	ADP	R	_	8	case	8:case	_

7	вчерашното	вчерашен	ADJ	Ansd	Definite=Def|Degree=Pos|Gender=Neut|Number=Sing	8	amod	8:amod	_

8	заседание	заседание	NOUN	Ncnsi	Definite=Ind|Gender=Neut|Number=Sing	5	nmod	5:nmod:на	_

9	по	по	ADP	R	_	10	case	10:case	_

10	делото	дело	NOUN	Ncnsd	Definite=Def|Gender=Neut|Number=Sing	8	nmod	8:nmod:по	_

11	срещу	срещу	ADP	R	_	12	case	12:case	_

12	шефа	шеф	NOUN	Ncmsh	Definite=Def|Gender=Masc|Number=Sing	10	nmod	10:nmod:срещу	_

13	на	на	ADP	R	_	14	case	14:case	_

14	пирамидата	пирамида	NOUN	Ncfsd	Definite=Def|Gender=Fem|Number=Sing	12	nmod	12:nmod:на	_

15	"	"	PUNCT	punct	_	16	punct	16:punct	SpaceAfter=No

16	Лайф	лайф	PROPN	Npmsi	Definite=Ind|Gender=Masc|Number=Sing	14	nmod	14:nmod	_

17	чойс	чойс	PROPN	Npmsi	Definite=Ind|Gender=Masc|Number=Sing	16	flat	16:flat	SpaceAfter=No

18	"	"	PUNCT	punct	_	16	punct	16:punct	SpaceAfter=No

19	.	.	PUNCT	punct	_	2	punct	2:punct	_



# sent_id = Standard-2000-10-24-s323

# text = Процесът вчера беше отложен пак, защото Капустин има нов адвокат.

1	Процесът	процес	NOUN	Ncmsf	Definite=Def|Gender=Masc|Number=Sing	4	nsubj:pass	4:nsubj:pass	_

2	вчера	вчера	ADV	Dt	Degree=Pos	4	advmod	4:advmod	_

3	беше	съм	AUX	Vxitf-t3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin|Voice=Act	4	aux	4:aux	_

4	отложен	отложа-(се)	VERB	Vpptcv--smi	Aspect=Perf|Definite=Ind|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass	0	root	0:root|9:advmod	_

5	пак	пак	ADV	Dt	Degree=Pos	4	advmod	4:advmod	SpaceAfter=No

6	,	,	PUNCT	punct	_	9	punct	9:punct	_

7	защото	защото	ADV	Prc	_	9	advmod	4:ref	_

8	Капустин	капустин	PROPN	Hmsi	Definite=Ind|Gender=Masc|Number=Sing	9	nsubj	9:nsubj	_

9	има	имам	VERB	Vpitf-r3s	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	4	advcl	4:advcl	_

10	нов	нов	ADJ	Amsi	Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing	11	amod	11:amod	_

11	адвокат	адвокат	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	9	obj	9:obj	SpaceAfter=No

12	.	.	PUNCT	punct	_	4	punct	4:punct	_



# sent_id = Standard-2000-10-24-s333

# text = Предоставил съм материалите на НСС.

1	Предоставил	предоставя	VERB	Vpptcao-smi	Aspect=Perf|Definite=Ind|Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part|Voice=Act	0	root	0:root	_

2	съм	съм	AUX	Vxitf-r1s	Aspect=Imp|Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin|Voice=Act	1	aux	1:aux	_

3	материалите	материал	NOUN	Ncmpd	Definite=Def|Gender=Masc|Number=Plur	1	obj	1:obj	_

4	на	на	ADP	R	_	5	case	5:case	_

5	НСС	нсс	PROPN	Npfsi	Definite=Ind|Gender=Fem|Number=Sing	1	obl	1:obl:на	SpaceAfter=No

6	.	.	PUNCT	punct	_	1	punct	1:punct	_



# sent_id = Standard-2000-10-24-s353

# text = Другият му мотив да се обърне към НСС бил Наказателният кодекс.

1	Другият	друг	ADJ	Amsf	Definite=Def|Degree=Pos|Gender=Masc|Number=Sing	3	amod	3:amod	_

2	му	мой	PRON	Psot--3--m	Person=3|Poss=Yes|PronType=Prs	1	det	1:det	_

3	мотив	мотив	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	11	nsubj	11:nsubj	_

4	да	да	AUX	Tx	_	6	aux	6:aux	_

5	се	се	PRON	Ppxta	Case=Acc|PronType=Prs|Reflex=Yes	6	expl	6:expl	_

6	обърне	обърна-(се)	VERB	Vpptf-r3s	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act	3	acl	3:acl	_

7	към	към	ADP	R	_	8	case	8:case	_

8	НСС	нсс	PROPN	Npfsi	Definite=Ind|Gender=Fem|Number=Sing	6	iobj	6:iobj	_

9	бил	съм	AUX	Vxitcat-smi	Aspect=Imp|Definite=Ind|Gender=Masc|Mood=Ind|Number=Sing|VerbForm=Part|Voice=Act	11	cop	11:cop	_

10	Наказателният	наказателен	ADJ	Amsf	Definite=Def|Degree=Pos|Gender=Masc|Number=Sing	11	amod	11:amod	_

11	кодекс	кодекс	NOUN	Ncmsi	Definite=Ind|Gender=Masc|Number=Sing	0	root	0:root	SpaceAfter=No

12	.	.	PUNCT	punct	_	11	punct	11:punct	_



# sent_id = Standard-2000-10-24-s370

# text = Регистрирани са през 1991 и 1995 г. на един и същи адрес в жк "Надежда", бл. 459, вх. В, ап. 65, където такава фирма сега няма.

1	Регистрирани	регистрирам	VERB	Vpptcv--p-i	Aspect=Perf|Definite=Ind|Number=Plur|VerbForm=Part|Voice=Pass	0	root	0:root	_


In [ ]:
lemmas

{'ултранационалистически',
 'придобивка',
 'настойчив',
 'бламирам',
 'динков',
 'иванкович',
 'смут',
 'поръмжа',
 'дванайсети',
 'противоположно',
 'бижу',
 'кацарова',
 'цветомир',
 'строя',
 'обвързвам-(се)',
 'повдигна-(се)',
 'вадя',
 'оркестър',
 'предубеждение',
 'обяд',
 'ататюрк',
 'отвред',
 'ниско',
 'левон',
 'виена',
 'алинея',
 'благородство',
 'човечество',
 '7000',
 'технически',
 'ненакърним',
 'съществено',
 'авторски',
 'престол',
 'непосилен',
 'молебен',
 'дете',
 'цялостност',
 'царуване',
 'новосибирск',
 '1987/1988',
 'учредителен',
 'маестро',
 'проектиране',
 'галин',
 'кастро',
 'нсбоп',
 'лорд',
 'булка',
 'инокентий',
 'разрез',
 'извия-(се)',
 'словения',
 'газстроймонтаж',
 'бачковски',
 'някъде',
 'шломо',
 'aes',
 'паркиране',
 'стремеж',
 'права',
 'мотор-институция',
 'задържа-(се)',
 'шетам',
 'акага',
 'следа',
 'занаят',
 'терор',
 'машина',
 'тежък',
 'bednar',
 'лила',
 '1995',
 'киносценарий',
 'огрея',
 'потъмнея',
 'доказване',
 'зачаквам',
 'утопически',
 'спирачен',
 'пропъждам',
 'инфекция',
 'австриец',
 'мачканов',
 'задвижа-(се)',
 'прелитане',
 'свързаност',
 'напускам',
 '4843,20',
 'природа',
 'фантазия',
 'избера',
 'колебание',
 'неритмичен',
 'сапунджиев',
 'пробив',
 'примитивен',
 'каталогизирам',
 'ясновидец',
 'божество',
 'атакувам',
 'формален',
 'лобирам',
 'футурист',
 'общинар',
 'регистрирам',
 'със',
 'дуло',
 'туркиня',
 'послушен',
 'построя-(се)',
 'лист',
 'аморузо',
 'преподавател',
 'изказвам-(се)',
 'млеко-',
 'девица',
 'виден',
 'карастоянова',
 'стил',
 'неловкост',
 'фитнес',
 'класиране',
 'късен',
 'запалителен',
 'украса',
 'марш',
 'осми',
 'тер-овсепян',
 'предпазя-(се)',
 'трайковски',
 'пекин',
 'минимизирам',
 '50:33',
 'утоля',
 'руша-(се)',
 'avoir',
 'батемберг',
 'анатомия',
 'мадридски',
 'самодоволство',
 'активен',
 'хотел',
 'катастрофален',
 'потреперя',
 'спра-(се)',
 'дърводобивен',
 'осигурителен',
 '107',
 'разведряване',
 'площадка',
 'фиджералд',
 'констанс',
 '1,15',
 'невръстен',
 'хайка',
 'работилница',
 'издъхна',
 'зона',
 'очарование',
 'люксембург',
 'мире',
 'ул.',
 'тротоар',
 'смешно',
 'почерк',
 'принадлежност',
 'любител',
 'есен',
 'уважа',
 '1991-92',
 'възраст',
 'щатен',
 'гърне',
 'попандов',
 'връзвам-(се)',
 'драголюб',
 'измеря',
 'фотос',
 'надойда',
 '9400',
 'емоционален',
 'изсипвам-(се)',
 'установя-(се)',
 'палат',
 'изработя',
 'фризьор',
 'пенсия',
 'стринка',
 'замирам',
 'брюкселски',
 'драстичен',
 'прихвам',
 'петстотингодишен',
 'клиент',
 'уж',
 'изпълком',
 'украся',
 'часовников',
 'гешева',
 'значи',
 'нигериец',
 'дс',
 'аеродинамичен',
 'фу',
 'разпозная',
 'карнавал',
 'мощен',
 'емигрирам',
 'светлана',
 'гу',
 'леден',
 'обичай',
 'принципно',
 'дарявам',
 'фотографирам',
 'възпирам-(се)',
 'обзървър',
 'спиране',
 'встрани',
 'австралия',
 'син',
 'предупредителен',
 'алън',
 'пусия',
 'клестил',
 'положително',
 'елуреди',
 'навляза',
 'доверие',
 'атински',
 'отечество',
 'светоглед',
 'брат',
 'бурен',
 'митничар',
 'визитка',
 'сподавя',
 'ментен',
 'допълнително',
 'безсилен',
 'база',
 'нормативен',
 'чета',
 'мода',
 'нива',
 '2007',
 'платини',
 'заедност',
 'дефектирам',
 'гара',
 'войн',
 '35',
 'превантивен',
 'полусезон',
 'субект',
 'ирония',
 'табла',
 'кротък',
 'ученик',
 'индивидуален',
 'скаутски',
 'прес',
 'момченце',
 'милион',
 'леснота',
 'нинов',
 'миг',
 'заживея',
 '1964',
 'юниън',
 'свиланович',
 'настъпя',
 'жени',
 'ребро',
 'неразумност',
 'тираж',
 'пазарен',
 'художничка',
 'бск',
 'преливам-(се)',
 'дийн',
 'интензивен',
 'претърсвам',
 'изгасна',
 'депресирам',
 'македонец',
 'росица',
 'вия-(се)',
 'генетически',
 'панайотов',
 'дестабилизирам-(се)',
 'повайкам-се',
 'ерик',
 'мо',
 'кукловод',
 'bug',
 'григор',
 'наблюдавам',
 'хазартен',
 'б',
 'дпс',
 'миналата-година',
 'върайъти',
 '34-годишният',
 'изпаря-(се)',
 'набиране',
 'шахматист',
 'чеков',
 'интересно',
 'облитам',
 'хапка',
 'влошавам-(се)',
 'първодивизионен',
 'продължаване',
 'опустошение',
 'сключа',
 'енигматичен',
 'повърхност',
 'викам',
 'извличане',
 'отписвам',
 'гърло',
 'експериментирам',
 'постигам',
 'шенген',
 'догледам',
 'меря-(се)',
 'женмин',
 'важен',
 'нелигитимен',
 'петер',
 'цефта',
 '1974',
 'разсмивам-(се)',
 'ганев',
 'включвам-(се)',
 'коктейл',
 'ненаказан',
 'предговор',
 'минавам-(се)',
 'тошев',
 'преразпределяне',
 'пергел',
 'комплимент',
 '41',
 ']',
 'нездрав',
 'моден',
 'инокентиев',
 'неверие',
 'окончателно',
 'каледония',
 'безгрижно',
 'владо',
 'олександър',
 'разпореждане',
 'лоялност',
 'йончев',
 'звънна',
 'каросерия',
 'маршрут',
 'подготвя-(се)',
 'светослав',
 'ниша',
 'етаж',
 'заловя-(се)',
 'пазарджик',
 'железница',
 'ройтерс',
 'кочина',
 'предотвратя',
 'брунко',
 'разясня-(се)',
 'пропаганда',
 'плод',
 'маньовър',
 'камерън',
 'предприемчивост',
 'веселба',
 'предлагане',
 'замък',
 'дилян',
 'сливналия',
 'пробия-(се)',
 'къпина',
 'клинг',
 'аз-ефективност',
 'информирам',
 'възбуждане',
 'митнически',
 'изявя-(се)',
 'трезв',
 'хърсев',
 'арогантно',
 'несправедлив',
 'медитация',
 'левски',
 'жилищен',
 'тридесет',
 'рупрехт',
 'коментирам',
 'предизборен',
 'летописец',
 'предупреждение',
 'уиски',
 'суперсила',
 'издължа-(се)',
 'северноатлантически',
 'притъпя-(се)',
 'болница',
 'филмотечен',
 'заслушвам-се',
 'загивам',
 'елементарен',
 'отговоря',
 'приканя',
 'фенклуб',
 'отрежа',
 'удовлетворяване',
 'василев',
 'венециански',
 'точа-(се)',
 'неизползване',
 'скъсвам',
 'азия',
 'босилеград',
 'запис',
 'име',
 'трясък',
 'уверявам-(се)',
 'примъкна-(се)',
 'смекчавам-(се)',
 'периодически',
 'сексуален',
 'сграбча',
 'снижаване',
 'експо',
 'заканя-се',
 'стамен',
 'посветя',
 'планиране',
 'изкъртя-(се)',
 'шегувам-се',
 'заколя',
 'хъдърсфийлд',
 'решавам-(се)',
 'следователно',
 'пинчев',
 'чудно',
 'фармацевтичен',
 'дружина',
 '56-годишна',
 'ауто',
 'бракониерство',
 'дилема',
 'раздразня-(се)',
 'торов',
 'харесам-(се)',
 'явление',
 'russo',
 'технологичен',
 'полски',
 'комба',
 'освобождавам-(се)',
 'пострадам',
 'бъкингамски',
 'час',
 'съпротива',
 'мента',
 'независимост',
 'всеотдаен',
 'лом',
 'наричам-(се)',
 'подозрение',
 'езеро',
 'тръбичка',
 'бзнс-нс',
 'заскърцам',
 'точа',
 'оригинал',
 'сакраменто',
 'новоселски',
 'обучение',
 'разкривя-(се)',
 'отчетлив',
 'детройт',
 'гудман',
 'механик',
 'болест',
 'източа-(се)',
 'лейк',
 'трима',
 'възприемам',
 'харманли',
 'осминафинал',
 'ултранационализм',
 'сезон',
 'пасажер',
 'редувам-(се)',
 'реконструкция',
 'осемдесети',
 'поевтинявам',
 'кабелен',
 'Христос',
 'посещаемост',
 'обкръжа',
 'агропромбанка',
 'гост',
 'гръб',
 'приятен',
 'навлизам',
 'подире',
 'научен',
 'милан',
 'стол',
 'расов',
 'руси',
 'дистанционен',
 'седмица',
 'терорист',
 'население',
 'гарантирам',
 'замествам',
 'ламарина',
 'премина',
 'тържествувам',
 'разпитвам',
 'обител',
 'топче',
 'ендокринолог',
 'писателка',
 'баск',
 'лина',
 'запъна-(се)',
 'оптимизъм',
 'директен',
 'благочестие',
 'зарежа',
 'навън',
 'неизяснен',
 'попреча',
 'документ',
 'кедров',
 'джуди',
 'прочит',
 'багдад',
 'изпадане',
 'кафе',
 'подготвям-(се)',
 'нефт',
 'зарко',
 'психологически',
 'каквото',
 'кино',
 'касета',
 '4500',
 '2,5',
 'кортеж',
 'интелект',
 'встъпителен',
 'фернандес',
 'август',
 'суверенен',
 'йон',
 'езерце',
 'депортиране',
 'съсипване',
 'критикувам',
 'заснема',
 'ситуация',
 'голд',
 'махна-(се)',
 'сливане',
 'стопя-(се)',
 'натрупване',
 'равновесие',
 'шкода',
 'лазаръс',
 'лозанов',
 'сръбна',
 'коричка',
 'съгласувам',
 'тоналност',
 'блок',
 'перфекционистка',
 'родилен',
 'предавам-(се)',
 'бодо',
 'проди',
 'простудя-(се)',
 'чифт',
 'имунен',
 'популярност',
 'телекомуникация',
 'аспарухов',
 'рекет',
 'развия-(се)',
 'херцеговина',
 'решителност',
 'освежаване',
 'отлично',
 'вергил',
 'шарпей',
 'чувство',
 'кабел',
 'русе',
 'ад',
 'раса',
 'букарев',
 'несъобразен',
 'допитам-се',
 'саут',
 'брюксел',
 'арменски',
 'готвач',
 'фамилия',
 'отклоня-(се)',
 'редакторка',
 'подсиля',
 'дике',
 'управа',
 '540',
 'върбанов',
 'обезвредя',
 'албански',
 'подмяна',
 'военнослужащ',
 'екстремизъм',
 'казачок',
 'мия',
 'зрелостен',
 'хавиер',
 'тютюнопушене',
 'машинописка',
 'разголване',
 'сполучлив',
 'хортувам',
 'съотечественик',
 'анастасия',
 'перничанин',
 'бандерол',
 'предпазен',
 'райчевски',
 'разказвам',
 'юнтуна',
 'и.д.',
 'динкински',
 '49-годишен',
 '?',
 'изказване',
 'кристален',
 'маратонски',
 'превес',
 'малта',
 'предизвикателство',
 'упование',
 'нелегално',
 'момчил',
 'тинка',
 'учен',
 'власт',
 'славков',
 'контрабанден',
 'константинов',
 'черта',
 'индже',
 'плътност',
 'шлем',
 'етем',
 'шум',
 '0,98',
 'писмен',
 'графика',
 'кълна',
 'петковски',
 'математически',
 'платежоспособен',
 'награден',
 'приемане',
 'достигна',
 'докарам-(се)',
 'преносен',
 'съвременник',
 'разузнавателен',
 'клеветнически',
 'изреченийце',
 'попмузика',
 'съекипник',
 'унгарски',
 'изгубен',
 'свържа',
 'запуша-(се)',
 'пиене',
 'погром',
 'южно',
 'капитализация',
 'прозрачен',
 'запазвам-(се)',
 '160',
 'разложки',
 'формуляр',
 'линейка',
 'сдам',
 'служене',
 'устие',
 'симон',
 'унищожа',
 'затворник',
 'елди',
 'безредица',
 'хайгроув',
 'задължа-(се)',
 'тояга',
 'затягам-(се)',
 'людмил',
 'въздушен',
 'бедствие',
 'хиляда',
 'английски',
 'градски',
 'ценович',
 'един',
 'байрам',
 'ей',
 'неприкосновен',
 'люпко',
 'заместник',
 'моментално',
 'холивудски',
 'плат',
 'спин',
 'стефан',
 'бензин',
 'коста',
 'пасмина',
 'крача',
 'седя',
 'намразя',
 'оличавам',
 'готов',
 'всичкия',
 'задоволя-(се)',
 'даже',
 'видимост',
 'залив',
 'изпробване',
 'лодка',
 'оправдаване',
 'любен',
 'салон',
 'т.нар.',
 'славчо',
 'макгомо',
 'облага',
 'надстрояване',
 'писукам',
 'керкенез',
 'държавнически',
 'минус',
 'филмопроизводство',
 'павилион',
 'инициативен',
 'установявам-(се)',
 'тото',
 'скулптурен',
 'конец',
 'бракониер',
 'прегръщам-(се)',
 'стомах',
 'възмездя',
 'розалия',
 'опровержение',
 'връхен',
 'ясемин',
 'секукуне',
 'олимпиада',
 'разлика',
 'бог',
 'парламентарист',
 'кебапче',
 'писна',
 'гей-олимпиада',
 'инго',
 'шоу',
 'подслаждане',
 'лекарка',
 'посея',
 'веле',
 'руски',
 'евроминистър',
 'компромат',
 'отред',
 'има',
 'мон',
 'разностранен',
 'еднакъв',
 'неизплатен',
 'махмурлия',
 'вадене',
 'заселване',
 'белослав',
 'фоайе',
 'посланически',
 'фермер',
 'нехомогенен',
 'меч',
 'изкупувам',
 'естество',
 'почна-(се)',
 'новогодишен',
 'алжир',
 'вземане',
 'кириак',
 'очертая-(се)',
 'знаме',
 'шантажирам',
 'консумация',
 'незабавен',
 'неподготвеност',
 'помръдвам-(се)',
 'излъжа-(се)',
 '48',
 'преизбера',
 'спасова',
 'полша',
 'австралийски',
 'узунова',
 'тор',
 'и',
 'ислямски',
 'морис',
 'съприкосновение',
 'плисна',
 'соис',
 'косовски',
 'франк',
 '24,66',
 'убеждавам-(се)',
 'измислям',
 'чума',
 'абордаж',
 'потвърдя',
 'лютви',
 'полигон',
 'напред',
 'георг',
 'банцинг',
 'сориа',
 'данов',
 'силистра',
 'налагане',
 'допусна',
 'четиричленен',
 '68',
 '02',
 'форум',
 'дървопреработвателен',
 'невски',
 'всякъде',
 'славчев',
 'шишенце',
 'убежище',
 'аптекар',
 'траволта',
 'панкаро',
 'тийнейджър',
 'холографски',
 'малцина',
 'нюпорт',
 'тиражирам',
 'размахам-(се)',
 'включа-(се)',
 '10,40',
 'ясен',
 'кондова',
 'емиграция',
 'замисъл',
 'социалист',
 'летовник',
 'нескафе',
 'струма',
 'снощи',
 'безмитен',
 'суров',
 'турнир',
 'татяна',
 'подплаша-(се)',
 'трепетно',
 'влага',
 'пестя-(се)',
 'сирак',
 'хепатит',
 'маратон',
 'пазаруване',
 'лъжица',
 'забравяне',
 'ограждение',
 'вроден',
 'гепи',
 'монах',
 'свят',
 'клаус',
 'опера',
 'phuwiangosaurus',
 'дрямка',
 'кладенче',
 'боздуган',
 'статус',
 'заместник-шефка',
 'недвижим',
 'коза',
 'напоследък',
 'песимист',
 'рисърч',
 'факт',
 'купя',
 'повишаване',
 'координата',
 'сменям-(се)',
 'предвид',
 'революционен',
 'колов',
 'луна',
 'месен',
 'лято',
 'илиева',
 'червенея-(се)',
 'губернатор-републиканец',
 'цайтунг',
 'приумица',
 'следобед',
 'осведомя-(се)',
 'отзоваване',
 'телеграма',
 'прилагане',
 '700000',
 'бенк',
 'назад',
 'чичибаба',
 'себеразрушителен',
 '8-9',
 'изневеряване',
 'сблъскам-(се)',
 'позакъснея',
 'майсторлък',
 'здраво',
 'техно',
 'премия',
 'обезлюдя-(се)',
 'извървя-(се)',
 'разпръсна-(се)',
 'алекс',
 'мътя-(се)',
 'виртуоз',
 'мирово',
 '471',
 'следен',
 'престъпник',
 'помен',
 'етап',
 'фъстък',
 'проклет',
 'безропотно',
 'хаинбоаз',
 'благодарност',
 'брава',
 'оплискам',
 'континент',
 'молдовски',
 'живописен',
 'стигане',
 'неканен',
 'крос',
 'софи',
 'негативен',
 'преизпълня-(се)',
 '155',
 '0,50',
 'познат',
 'агитка',
 'мануел',
 'градец',
 'топъл',
 'разчета-(се)',
 'късно',
 'реалист',
 'навремето',
 'подсъдим',
 'двайсет',
 'производител',
 'указ',
 'запарка',
 'преподобен',
 'мерцедес-бенц',
 'д',
 'еквивалент',
 'пръстено-жълт',
 'венецуелски',
 'пречупя-(се)',
 ...}

In [ ]:
ta_lemmas = [lemma for lemma in lemmas if lemma.endswith("та")]

In [ ]:
ta_lemmas

['чета',
 'леснота',
 'цефта',
 'мента',
 'касета',
 'малта',
 'черта',
 'коста',
 'траволта',
 'координата',
 'заплата',
 'предпочета',
 '37-ата',
 'нафта',
 'минута',
 'работа',
 '53-ата',
 'анита',
 '28-годишната',
 'джакарта',
 'невеста',
 'санта',
 '21-та',
 'белота',
 'срамота',
 'чистота',
 '27-годишната',
 'харта',
 'валета',
 'оферта',
 'яхта',
 'карта',
 'регата',
 '5-ата',
 'помета',
 'порта',
 'прочета',
 'визита',
 '89-ата',
 'та',
 '74-ата',
 'мечта',
 'никита',
 'афродита',
 'пета',
 'ранглиста',
 'маргита',
 'марта',
 'атланта',
 'артфиеста',
 'делта',
 'рмд-та',
 'пшеничката',
 '52-та',
 'лента',
 'уста',
 'щафета',
 'галата',
 '65-годишната',
 'лопата',
 'висота',
 '43-годишната',
 'лепта',
 '22-годишната',
 'дочета',
 'доста',
 'писта',
 'монета',
 'лаута',
 'диета',
 'рецепта',
 'салата',
 'херта',
 'охота',
 'субота',
 'анкета',
 'палата',
 '44-годишната',
 'бета',
 'пустота',
 'бта',
 'орбита',
 'просвета',
 '45-часовата',
 'защита',
 'двеста',
 'вендета',
 '22-рата',
 '35-годишната',
 'валута',
 'видеокасета',
 'венета',
 'антоанета',
 'пафта',
 'самота',
 'соната',
 'ракета',
 'дата',
 'обраста',
 'триста',
 'топлота',
 'листа',
 'конфета',
 'виолета',
 'ета',
 'муфата',
 'ефта',
 'жулиета',
 'аталанта',
 'събота',
 'минесота',
 'красота',
 'пту-тата',
 'почета',
 'калиста',
 'банкнота',
 'раста',
 'ренета',
 'планета',
 'врата',
 'рота',
 'яснота',
 'жорета',
 'квота',
 'паста',
 '42-годишната',
 'простота',
 'правота',
 'клевета',
 'еврохарта',
 '69-ата',
 'голота',
 'листата',
 'реколта',
 'здравата',
 '153-ата',
 'мета',
 'плета',
 'чанта',
 'маргарита',
 'щета',
 'нота',
 'кнесета',
 'граната']